version: "3.8"
services:
  frontend:
    restart: always
    command: npm start
    container_name: frontend
    build:
      context: ./jansori
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true